# Note to self: the username and password are not used when the app is deployed
# in Heroku, see https://devcenter.heroku.com/articles/rails-database-connection-behavior
# Settings here only apply to local dev environment

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dojo
  password:

production:
  <<: *default
  database: dojo_production

development:
  <<: *default
  database: dojo_development

test:
  <<: *default
  database: dojo_test
